# Which Google Sheet to read/write
google_sheets:
  sheet_id: "1qcEIA02LoL28KzUysCg_6PXDPP22p6NijOzIgOK6p3w"
  monitors_tab: "Monitors"
  alerts_tab: "Alerts_Log"

  # Path to the Google service account credentials file on disk.
  # This is the JSON file you download from Google Cloud.
  service_account_json: "/home/luiscarlosht/WeinsteinAgent/creds/gcp_service_account.json"
  client_email: "500633565449-compute@developer.gserviceaccount.com"

# Email alert settings
email:
  from: "luiscarlosht@gmail.com"
  to:
    - "luiscarloshernandez@hotmail.com"
    - "luiscarlosht@gmail.com"
  smtp_host: "smtp.gmail.com"
  smtp_port: 587
  smtp_user: "luiscarlosht@gmail.com"
  smtp_pass: "qnamoxtmakhnvlml"

# OpenAI model settings
openai:
  api_key: "CHANGE_ME_OPENAI_KEY"
  model: "gpt-5-thinking"
  # we'll hint that browsing is allowed
  extra_headers:
    X-Allow-Browsing: "true"

# Run options / policy
scan_defaults:
  # fallback seats if not provided in sheet row
  default_seats: 2

  # if sheet row's MaxPricePerPersonUSD is blank,
  # we treat threshold as very high and won't alert unless it's insanely low
  default_threshold: 9999

  # airport radius logic
  home_fallback: "Mansfield, TX"
  default_origin_airports: ["DFW", "DAL"]

security:
  # where to write logs
  log_file: "/home/luiscarlosht/AffordableFamilyVacation/monitor/monitor.log"
